# Generated by Django 6.0.3 on 2026-03-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nicho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('propietario', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_difunto', models.CharField(blank=True, max_length=200, null=True)),
                ('monto_arbitrio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('foto_nicho', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('esta_exhumado', models.BooleanField(default=False)),
                ('acta_exhumacion', models.FileField(blank=True, null=True, upload_to='actas/')),
                ('notas_legales', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
