# Generated by Django 4.2.28 on 2026-03-02 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nicho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('nombre_difunto', models.TextField(blank=True, null=True, verbose_name='Nombres de Difuntos')),
                ('estado_id', models.BigIntegerField(default=1)),
                ('propietario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dueño Legal')),
                ('dpi_propietario', models.CharField(blank=True, max_length=15, null=True, verbose_name='DPI')),
                ('numero_titulo', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. de Título/Escritura')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Notas de Propiedad')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='nichos/', verbose_name='Foto del Nicho')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Último Pago')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('monto_arbitrio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto de Arbitrio (Q)')),
            ],
        ),
        migrations.CreateModel(
            name='FotoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inspecciones/%Y/%m/%d/')),
                ('fecha_toma', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('nicho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='registros.nicho')),
            ],
            options={
                'verbose_name_plural': 'Fotos de Campo',
            },
        ),
        migrations.CreateModel(
            name='Exhumacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_exhumacion', models.DateField(verbose_name='Fecha de la Exhumación')),
                ('nombre_difunto_retirado', models.CharField(max_length=200, verbose_name='Nombre del Difunto Retirado')),
                ('solicitante', models.CharField(max_length=200, verbose_name='Familiar que solicita / Autoridad')),
                ('documento_autorizacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. de Oficio o Acta')),
                ('destino_restos', models.CharField(max_length=255, verbose_name='Destino de los restos (Osario/Otro)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Notas del Proceso')),
                ('nicho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumaciones', to='registros.nicho', verbose_name='Nicho Relacionado')),
            ],
            options={
                'verbose_name': 'Exhumación',
                'verbose_name_plural': 'Exhumaciones',
            },
        ),
    ]
