# Generated by Django 5.2.8 on 2026-01-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nicho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('nombre_difunto', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_id', models.BigIntegerField(default=1)),
            ],
        ),
    ]
