# Generated by Django 5.2.8 on 2026-01-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicho',
            name='dpi_propietario',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='DPI'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='numero_titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. de Título/Escritura'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de Propiedad'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='propietario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dueño Legal'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='nombre_difunto',
            field=models.TextField(blank=True, null=True, verbose_name='Nombres de Difuntos'),
        ),
    ]
