# Generated by Django 6.0.3 on 2026-03-06 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(verbose_name='Detalles del hallazgo')),
                ('nivel_urgencia', models.CharField(choices=[('LEVE', 'Leve (Pintura/Limpieza)'), ('MODERADO', 'Moderado (Grietas/Lápida)'), ('CRITICO', 'Crítico (Riesgo Estructural)')], default='LEVE', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', '🔴 Pendiente'), ('EN_PROCESO', '🟡 En Proceso'), ('RESUELTO', '🟢 Resuelto')], default='PENDIENTE', max_length=15)),
                ('reportado_por', models.CharField(max_length=100)),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='danos/')),
                ('nicho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_danos', to='registros.nicho')),
            ],
            options={
                'verbose_name': 'Reporte de Daño',
                'verbose_name_plural': 'Control de Daños y Mantenimiento',
            },
        ),
    ]
