# Generated by Django 4.2.28 on 2026-03-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotocampo',
            name='nicho',
        ),
        migrations.AlterModelOptions(
            name='nicho',
            options={'verbose_name': 'Nicho', 'verbose_name_plural': 'Control de Nichos'},
        ),
        migrations.RemoveField(
            model_name='nicho',
            name='dpi_propietario',
        ),
        migrations.RemoveField(
            model_name='nicho',
            name='estado_id',
        ),
        migrations.RemoveField(
            model_name='nicho',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='nicho',
            name='numero_titulo',
        ),
        migrations.RemoveField(
            model_name='nicho',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='nicho',
            name='telefono_contacto',
        ),
        migrations.AddField(
            model_name='nicho',
            name='documento_propiedad',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Título Escaneado (PDF)'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='esta_exhumado',
            field=models.BooleanField(default=False, verbose_name='¿Fue Exhumado?'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='fecha_exhumacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Exhumación'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='foto_nicho',
            field=models.ImageField(blank=True, null=True, upload_to='nichos_fotos/', verbose_name='Foto del Estado Actual'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='notas_internas',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de Campo'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='orden_exhumacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Oficio/Orden'),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de Nicho'),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Último Pago'),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento'),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='monto_arbitrio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='nombre_difunto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Difunto'),
        ),
        migrations.DeleteModel(
            name='Exhumacion',
        ),
        migrations.DeleteModel(
            name='FotoCampo',
        ),
    ]
