# Generated by Django 6.0.3 on 2026-03-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_reportedano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportedano',
            options={'verbose_name': 'Reporte de Daño', 'verbose_name_plural': 'Control de Daños'},
        ),
        migrations.AlterField(
            model_name='reportedano',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reportedano',
            name='nivel_urgencia',
            field=models.CharField(choices=[('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('CRITICO', 'Crítico')], default='LEVE', max_length=10),
        ),
    ]
