# Generated by Django 5.2.8 on 2026-01-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_nicho_dpi_propietario_nicho_numero_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicho',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Último Pago'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='nichos/', verbose_name='Foto del Nicho'),
        ),
    ]
