# Generated by Django 4.2.28 on 2026-03-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_remove_fotocampo_nicho_alter_nicho_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nicho',
            options={},
        ),
        migrations.RemoveField(
            model_name='nicho',
            name='documento_propiedad',
        ),
        migrations.RemoveField(
            model_name='nicho',
            name='fecha_exhumacion',
        ),
        migrations.RemoveField(
            model_name='nicho',
            name='notas_internas',
        ),
        migrations.RemoveField(
            model_name='nicho',
            name='orden_exhumacion',
        ),
        migrations.AddField(
            model_name='nicho',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrs/'),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='esta_exhumado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='foto_nicho',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='nombre_difunto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nicho',
            name='propietario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
