# Generated by Django 6.0.3 on 2026-03-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_reportedano_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedano',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportedano',
            name='foto_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='danos/'),
        ),
        migrations.AlterField(
            model_name='reportedano',
            name='reportado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
