# Generated by Django 5.2.8 on 2026-01-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_nicho_fecha_pago_nicho_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inspecciones/%Y/%m/%d/')),
                ('fecha_toma', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('nicho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='registros.nicho')),
            ],
            options={
                'verbose_name': 'Fotos de Campo',
            },
        ),
    ]
