# Generated by Django 4.2.28 on 2026-03-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_nicho_options_remove_nicho_documento_propiedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicho',
            name='acta_exhumacion',
            field=models.FileField(blank=True, null=True, upload_to='actas/'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='notas_legales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
