# Generated by Django 6.0.3 on 2026-03-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_reportedano_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicho',
            name='titulo_propiedad',
            field=models.FileField(blank=True, null=True, upload_to='titulos/'),
        ),
    ]
