# Generated by Django 5.2.8 on 2026-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_fotocampo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicho',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='monto_arbitrio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto de Arbitrio (Q)'),
        ),
    ]
