# Generated by Django 5.2.8 on 2026-02-11 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_nicho_fecha_vencimiento_nicho_monto_arbitrio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhumacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_exhumacion', models.DateField(verbose_name='Fecha de la Exhumación')),
                ('nombre_difunto_retirado', models.CharField(max_length=200, verbose_name='Nombre del Difunto Retirado')),
                ('solicitante', models.CharField(max_length=200, verbose_name='Familiar que solicita / Autoridad')),
                ('documento_autorizacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. de Oficio o Acta')),
                ('destino_restos', models.CharField(max_length=255, verbose_name='Destino de los restos (Osario/Otro)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Notas del Proceso')),
                ('nicho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumaciones', to='registros.nicho', verbose_name='Nicho Relacionado')),
            ],
            options={
                'verbose_name': 'Exhumación',
                'verbose_name_plural': 'Exhumaciones',
            },
        ),
    ]
