# Generated by Django 6.0.3 on 2026-03-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_nicho_titulo_propiedad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nicho',
            old_name='acta_exhumacion',
            new_name='archivo_acta',
        ),
        migrations.RenameField(
            model_name='nicho',
            old_name='titulo_propiedad',
            new_name='archivo_titulo',
        ),
        migrations.AddField(
            model_name='nicho',
            name='numero_acta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Acta'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='numero_formulario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Formulario'),
        ),
        migrations.AddField(
            model_name='nicho',
            name='numero_titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Título'),
        ),
    ]
