# Generated by Django 5.2.8 on 2026-02-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_exhumacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotocampo',
            options={'verbose_name_plural': 'Fotos de Campo'},
        ),
    ]
