# Generated by Django 6.0.3 on 2026-03-08 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_rename_acta_exhumacion_nicho_archivo_acta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoArbitrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('numero_recibo', models.CharField(max_length=50, verbose_name='No. Recibo Municipal')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Q.')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('nicho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_historial', to='registros.nicho')),
            ],
            options={
                'verbose_name': 'Historial de Pago',
                'verbose_name_plural': 'Historial de Pagos',
            },
        ),
    ]
