# Generated by Django 6.0.2 on 2026-02-22 16:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_alter_fotocampo_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nicho',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='qrcodes/'),
        ),
        migrations.CreateModel(
            name='HistoricalNicho',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('nombre_difunto', models.TextField(blank=True, null=True, verbose_name='Nombres de Difuntos')),
                ('estado_id', models.BigIntegerField(default=1)),
                ('propietario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dueño Legal')),
                ('dpi_propietario', models.CharField(blank=True, max_length=15, null=True, verbose_name='DPI')),
                ('numero_titulo', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. de Título/Escritura')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Notas de Propiedad')),
                ('foto', models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto del Nicho')),
                ('qr_code', models.TextField(blank=True, editable=False, max_length=100, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Último Pago')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('monto_arbitrio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto de Arbitrio (Q)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical nicho',
                'verbose_name_plural': 'historical nichos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
