# Generated by Django 6.0.3 on 2026-03-08 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_pagoarbitrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nicho',
            name='numero_acta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Acta Actual'),
        ),
        migrations.CreateModel(
            name='ActaExhumacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proceso', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('ADMINISTRATIVA', '🏛️ Municipal (Mora/Vencimiento)'), ('JUDICIAL', '⚖️ Judicial (Orden MP/Juez)'), ('FAMILIAR', '👨\u200d👩\u200d👦 Familiar (Voluntaria)'), ('SANITARIA', '☣️ Sanitaria (Salud Pública)')], default='ADMINISTRATIVA', max_length=20)),
                ('numero_acta', models.CharField(help_text='Ej: ACTA-2026-001', max_length=50, unique=True)),
                ('solicitante_nombre', models.CharField(max_length=200, verbose_name='Nombre del Requirente')),
                ('solicitante_dpi', models.CharField(max_length=20, verbose_name='DPI / CUI')),
                ('solicitante_parentesco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parentesco')),
                ('destino_restos', models.CharField(help_text='Ej: Osario General, Traslado a Guatemala, etc.', max_length=200)),
                ('observaciones_legales', models.TextField(blank=True, null=True)),
                ('responsable_muni', models.CharField(max_length=100, verbose_name='Administrador en Turno')),
                ('nicho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_actas', to='registros.nicho')),
            ],
            options={
                'verbose_name': 'Acta de Exhumación',
                'verbose_name_plural': 'Libro de Actas de Exhumación',
                'ordering': ['-fecha_proceso'],
            },
        ),
    ]
