# Generated by Django 6.0.3 on 2026-03-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_alter_nicho_numero_acta_actaexhumacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaexhumacion',
            name='archivo_respaldo',
            field=models.FileField(blank=True, help_text='Suba el PDF o Foto del Oficio del MP o Solicitud Familiar.', null=True, upload_to='respaldos_actas/', verbose_name='Documento de Respaldo'),
        ),
        migrations.AlterField(
            model_name='actaexhumacion',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRATIVA', '🏛️ Municipal (Mora/Vencimiento)'), ('JUDICIAL', '⚖️ Judicial (Orden MP/Juez)'), ('FAMILIAR', '👨👩👦 Familiar (Voluntaria)'), ('SANITARIA', '☣️ Sanitaria (Salud Pública)')], default='ADMINISTRATIVA', max_length=20),
        ),
    ]
