# Generated by Django 6.0.3 on 2026-03-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_actaexhumacion_archivo_respaldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedano',
            name='fecha_solucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Reparación'),
        ),
        migrations.AddField(
            model_name='reportedano',
            name='foto_reparacion',
            field=models.FileField(blank=True, null=True, upload_to='reparaciones/', verbose_name='Foto Reparado (Después)'),
        ),
        migrations.AddField(
            model_name='reportedano',
            name='notas_reparacion',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de la Reparación'),
        ),
        migrations.AlterField(
            model_name='actaexhumacion',
            name='archivo_respaldo',
            field=models.FileField(blank=True, null=True, upload_to='respaldos_actas/', verbose_name='Documento de Respaldo'),
        ),
        migrations.AlterField(
            model_name='reportedano',
            name='foto_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='danos/', verbose_name='Foto del Daño (Antes)'),
        ),
    ]
